export const ACTION_CHANGE_CURRENT_COLOR = 'ACTION_CHANGE_CURRENT_COLOR';

export const ACTION_CHANGE_DISPLAY_SLIDERS_MENU = 'ACTION_CHANGE_DISPLAY_SLIDERS_MENU';

export const ACTION_CHANGE_DISPLAY_COLORS_MENU = 'ACTION_CHANGE_DISPLAY_COLORS_MENU';